// Added: same class list as frontend src/lib/class-options.ts (keep in sync).
export const STUDENT_CLASS_OPTIONS = [
  "Creche",
  "Nursery 1",
  "Nursery 2",
  "Nursery 3",
  "Primary 1",
  "Primary 2",
  "Primary 3",
  "Primary 4",
  "Primary 5",
  "JSS 1",
  "JSS 2",
  "JSS 3",
  "SS1 Art",
  "SS1 Commercial",
  "SS1 Science",
  "SS2 Art",
  "SS2 Commercial",
  "SS2 Science",
  "SS3 Art",
  "SS3 Commercial",
  "SS3 Science",
];
